rule Compromise_Greece_Beijing
{
	strings:
		$URL1 = "https://twitter.com/PhysicalDrive0/status/479921770838102017"
		$URL2 = "http://www.grpressbeijing.com/1.jar"
		$Filename1 = "1.jar"
		$Filename2 = "1.jar"
		$Host1 = "www.grpressbeijing.com"
		$SHA2561 = "b832e4b5a4829c8df6de7b42c5cb32ef25b5ab59072b4c2a7838404cd0dd5e5f"
		$Registry1 = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet"
		$Registry2 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry3 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry4 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry5 = "HKCU\\Software\\Microsoft\\Internet"
		$IP1 = "208.115.124.83"
		$Filename3 = "cmd.exe"
		$Filename4 = "cmd.exe"
		$Host2 = "defense.miraclecz.com"
		$Registry6 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry7 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry8 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry9 = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet"
		$Registry10 = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet"
		$Registry11 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry12 = "HKCU\\Software\\Microsoft\\Internet"
		$URL3 = "http://www.motobit.com/util/base64-decoder-encoder.asp"
		$Host3 = "defense.miraclecz.com"
		$Host4 = "www.motobit.com"
		$SHA2562 = "a4863f44f48d1c4c050dd7baad767a86b348dd4d33924acf4e0a3cd40c6ae29f"
		$URL4 = "http://buy.miraclecz.com"
		$Filename5 = "spoolsv.exe"
		$Filename6 = "spoolsv.exe"
		$Filename7 = "spoolsv.exe"
		$Filename8 = "cmd.exe"
		$Host5 = "buy.miraclecz.com"
		$Registry13 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry14 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry15 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry16 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry17 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry18 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry19 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry20 = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet"
		$Registry21 = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet"
		$Registry22 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry23 = "HKCU\\Software\\Microsoft\\Internet"
		$Registry24 = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"
		$URL5 = "https://www.dropbox.com/s/ckr7p5kka62cc7s/Embassy%20of%20Greece%20-%20Beijing.zip"
		$IP2 = "74.121.191.33"
		$Filename9 = "cmd.exe"
		$Filename10 = "20Beijing.zip"
		$Host6 = "buy.miraclecz.com"
	condition:
		$URL1 or $URL2 or $Filename1 or $Filename2 or $Host1 or $SHA2561 or $Registry1 or $Registry2 or $Registry3 or $Registry4 or $Registry5 or $IP1 or $Filename3 or $Filename4 or $Host2 or $Registry6 or $Registry7 or $Registry8 or $Registry9 or $Registry10 or $Registry11 or $Registry12 or $URL3 or $Host3 or $Host4 or $SHA2562 or $URL4 or $Filename5 or $Filename6 or $Filename7 or $Filename8 or $Host5 or $Registry13 or $Registry14 or $Registry15 or $Registry16 or $Registry17 or $Registry18 or $Registry19 or $Registry20 or $Registry21 or $Registry22 or $Registry23 or $Registry24 or $URL5 or $IP2 or $Filename9 or $Filename10 or $Host6
}