rule cto_tib_20150420_01a
{
	strings:
		$Email1 = "threatintelligence@uk.pwc"
		$URL1 = "https://www.fireeye.com/blog/threat-research/2015/04/probable_apt28_useo.html"
		$URL2 = "http://pwc.blogs.com/files/tactical-intelligence-bulletin---sofacy-phishing-.pdf"
		$URL3 = "https://twitter.com/ThreatConnect/status/589168650759884800"
		$Filename1 = "probable_apt28_useo.html"
		$Filename2 = "tactical-intelligence-bulletin---sofacy-phishing-.pdf"
		$Host1 = "pwc.blogs.com"
		$SHA2561 = "67ecc3b8c6057090c7982883e8d9d0389a8a8f6e8b00f9e9b73c45b008241322"
		$CVE1 = "CVE-2015-3043"
		$CVE2 = "CVE-2015-1701"
		$Email2 = "threatintelligence@uk.pwc"
		$Host2 = "defencereview.net"
		$Host3 = "brnlv-gv.eu"
		$Host4 = "militaryobserver.net"
		$Host5 = "netassistcache.com"
		$Host6 = "asus-service.net"
		$Host7 = "aolnets.com"
		$Host8 = "natopress.org"
		$Host9 = "natopress.com"
		$Host10 = "defencereview.eu"
		$Host11 = "intelsupport.net"
		$Host12 = "globalnewsweekly.com"
		$Host13 = "osce-oscc.org"
		$Host14 = "enisa-europa.com"
		$Host15 = "enisa-europa.org"
		$Host16 = "techcruncln.com"
		$Host17 = "nato-hq.com"
		$Host18 = "iacr-tcc.org"
		$Host19 = "nato-int.com"
		$Host20 = "nato-info.com"
		$Host21 = "bmlv-gv.eu"
		$Host22 = "foreignreview.com"
		$Host23 = "mediarea.org"
		$Host24 = "osce-military.org"
		$Host25 = "europeanda.com"
		$Host26 = "softupdates.info"
		$Host27 = "settings-yahoo.com"
		$Host28 = "settings-live.com"
		$Host29 = "delivery-yahoo.com"
		$Host30 = "privacy-yahoo.com"
		$Host31 = "privacy-live.com"
		$Host32 = "westinqhousenuclear.com"
		$Host33 = "webmail.westinqhousenuclear.com"
		$URL4 = "http://pwc.blogs.com/cyber_security_updates/2014/10/phresh-phishing-against"
		$URL5 = "http://pwc.blogs.com/files/tactical-intelligence-bulletin---sofacy-phishing-.pdf"
		$URL6 = "https://www.fireeye.com/resources/pdfs/apt28.pdf"
		$URL7 = "http://pwc.blogs.com/cyber_security_updates/2014/12/apt28-sofacy-so-funny.html"
		$URL8 = "https://www.fireeye.com/blog/threat-research/2015/04/probable_apt28_useo.html"
		$Filename3 = "government-defence-and-energy.html"
		$Filename4 = "tactical-intelligence-bulletin---sofacy-phishing-.pdf"
		$Filename5 = "wp-operation-pawn-storm.pdf"
		$Filename6 = "apt28.pdf"
		$Filename7 = "apt28-sofacy-so-funny.html"
		$Filename8 = "probable_apt28_useo.html"
		$Host34 = "www.welivesecurity.com"
		$Host35 = "pwc.blogs.com"
		$Host36 = "pwc.blogs.com"
		$Host37 = "pwc.blogs.com"
	condition:
		$Email1 or $URL1 or $URL2 or $URL3 or $Filename1 or $Filename2 or $Host1 or $SHA2561 or $CVE1 or $CVE2 or $Email2 or $Host2 or $Host3 or $Host4 or $Host5 or $Host6 or $Host7 or $Host8 or $Host9 or $Host10 or $Host11 or $Host12 or $Host13 or $Host14 or $Host15 or $Host16 or $Host17 or $Host18 or $Host19 or $Host20 or $Host21 or $Host22 or $Host23 or $Host24 or $Host25 or $Host26 or $Host27 or $Host28 or $Host29 or $Host30 or $Host31 or $Host32 or $Host33 or $URL4 or $URL5 or $URL6 or $URL7 or $URL8 or $Filename3 or $Filename4 or $Filename5 or $Filename6 or $Filename7 or $Filename8 or $Host34 or $Host35 or $Host36 or $Host37
}