rule DECLAWING_THE_DRAGON
{
	strings:
		$URL1 = "http://www.china.org.cn/english"
		$URL2 = "http://www.uscc.gov/annual_report/2007/report_to_congress.pdf"
		$URL3 = "http://www.newsweek.com"
		$URL4 = "http://www.whitehouse.gov"
		$URL5 = "http://www.usatoday.com"
		$URL6 = "http://www.gcn.com/print/25_25/41716-1.html?page=2"
		$URL7 = "http://searchsecurity.techtarget.com/news/article/0,289142,sid14_gci1301833,00.html"
		$URL8 = "http://www.npr.org/templates/story/story.php?storyId=6923805"
		$URL9 = "http://www.freedomdomain.com/weathercontrol/jointhearing.html"
		$URL10 = "http://www.au.af.mil/au/aunews/archive"
		$Filename1 = "194421.htm"
		$Filename2 = "report_to_congress.pdf"
		$Filename3 = "maritime-security.html"
		$Filename4 = "2007-04-18-2250474372_x.htm"
		$Filename5 = "41716-1.html"
		$Filename6 = "00.html"
		$Filename7 = "jointhearing.html"
		$Filename8 = "CyberspaceDefined.html"
		$Host1 = "www.china.org.cn"
		$Host2 = "www.uscc.gov"
		$Host3 = "www.newsweek.com"
		$Host4 = "www.whitehouse.gov"
		$Host5 = "www.usatoday.com"
		$Host6 = "www.gcn.com"
		$Host7 = "searchsecurity.techtarget.com"
		$Host8 = "www.npr.org"
		$Host9 = "www.freedomdomain.com"
		$Host10 = "www.au.af.mil"
		$URL11 = "http://www.time.com/time/magazine"
		$URL12 = "http://www.china.org.cn/english/12150.htm"
		$Filename9 = "12150.htm"
		$Host11 = "www.kobudi.co.id"
		$Host12 = "www.juntuan.cn"
		$URL13 = "http://commons.wikimedia.org/wiki/File:China%E2%80%99s_"
		$Filename10 = "Military_Regions.png"
		$Host13 = "commons.wikimedia.org"
		$URL14 = "http://www.strategycenter.net/research"
		$Host14 = "www.strategycenter.net"
		$URL15 = "http://www.strategycenter.net/research/pubID.191/pub_detail.asp"
		$URL16 = "http://www.nps.edu/Admissions/Catalog/index.html"
		$Filename11 = "index.html"
		$Host15 = "www.nps.edu"
		$Host16 = "www.sinodefence.com"
		$URL17 = "http://www.uscc.gov/annual_report/2007"
		$URL18 = "http://searchsecurity.techtarget.com/news/article"
		$URL19 = "http://www.usatoday.com/tech/products/2007-04-18-2250474372_x.htm"
		$URL20 = "http://www.au.af.mil/au/aunews"
		$URL21 = "http://www.newsweek.com/id/47443/page/3"
		$URL22 = "http://www.freedomdomain.com/weathercontrol"
		$URL23 = "http://www.whitehouse.gov/homeland/maritime-security.html"
		$URL24 = "http://www.china.org.cn/english/features"
		$URL25 = "http://en.wikipedia.org/wiki"
	condition:
		$URL1 or $URL2 or $URL3 or $URL4 or $URL5 or $URL6 or $URL7 or $URL8 or $URL9 or $URL10 or $Filename1 or $Filename2 or $Filename3 or $Filename4 or $Filename5 or $Filename6 or $Filename7 or $Filename8 or $Host1 or $Host2 or $Host3 or $Host4 or $Host5 or $Host6 or $Host7 or $Host8 or $Host9 or $Host10 or $URL11 or $URL12 or $Filename9 or $Host11 or $Host12 or $URL13 or $Filename10 or $Host13 or $URL14 or $Host14 or $URL15 or $URL16 or $Filename11 or $Host15 or $Host16 or $URL17 or $URL18 or $URL19 or $URL20 or $URL21 or $URL22 or $URL23 or $URL24 or $URL25
}rule DECLAWING_THE_DRAGON
{
	strings:
		$URL1 = "http://www.china.org.cn/english"
		$URL2 = "http://www.uscc.gov/annual_report/2007/report_to_congress.pdf"
		$URL3 = "http://www.newsweek.com"
		$URL4 = "http://www.whitehouse.gov"
		$URL5 = "http://www.usatoday.com"
		$URL6 = "http://www.gcn.com/print/25_25/41716-1.html?page=2"
		$URL7 = "http://searchsecurity.techtarget.com/news/article/0,289142,sid14_gci1301833,00.html"
		$URL8 = "http://www.npr.org/templates/story/story.php?storyId=6923805"
		$URL9 = "http://www.freedomdomain.com/weathercontrol/jointhearing.html"
		$URL10 = "http://www.au.af.mil/au/aunews/archive"
		$Filename1 = "194421.htm"
		$Filename2 = "report_to_congress.pdf"
		$Filename3 = "maritime-security.html"
		$Filename4 = "2007-04-18-2250474372_x.htm"
		$Filename5 = "41716-1.html"
		$Filename6 = "00.html"
		$Filename7 = "jointhearing.html"
		$Filename8 = "CyberspaceDefined.html"
		$Host1 = "www.china.org.cn"
		$Host2 = "www.uscc.gov"
		$Host3 = "www.newsweek.com"
		$Host4 = "www.whitehouse.gov"
		$Host5 = "www.usatoday.com"
		$Host6 = "www.gcn.com"
		$Host7 = "searchsecurity.techtarget.com"
		$Host8 = "www.npr.org"
		$Host9 = "www.freedomdomain.com"
		$Host10 = "www.au.af.mil"
		$URL11 = "http://www.time.com/time/magazine"
		$URL12 = "http://www.china.org.cn/english/12150.htm"
		$Filename9 = "12150.htm"
		$Host11 = "www.kobudi.co.id"
		$Host12 = "www.juntuan.cn"
		$URL13 = "http://commons.wikimedia.org/wiki/File:China%E2%80%99s_"
		$Filename10 = "Military_Regions.png"
		$Host13 = "commons.wikimedia.org"
		$URL14 = "http://www.strategycenter.net/research"
		$Host14 = "www.strategycenter.net"
		$URL15 = "http://www.strategycenter.net/research/pubID.191/pub_detail.asp"
		$URL16 = "http://www.nps.edu/Admissions/Catalog/index.html"
		$Filename11 = "index.html"
		$Host15 = "www.nps.edu"
		$Host16 = "www.sinodefence.com"
		$URL17 = "http://www.uscc.gov/annual_report/2007"
		$URL18 = "http://searchsecurity.techtarget.com/news/article"
		$URL19 = "http://www.usatoday.com/tech/products/2007-04-18-2250474372_x.htm"
		$URL20 = "http://www.au.af.mil/au/aunews"
		$URL21 = "http://www.newsweek.com/id/47443/page/3"
		$URL22 = "http://www.freedomdomain.com/weathercontrol"
		$URL23 = "http://www.whitehouse.gov/homeland/maritime-security.html"
		$URL24 = "http://www.china.org.cn/english/features"
		$URL25 = "http://en.wikipedia.org/wiki"
	condition:
		$URL1 or $URL2 or $URL3 or $URL4 or $URL5 or $URL6 or $URL7 or $URL8 or $URL9 or $URL10 or $Filename1 or $Filename2 or $Filename3 or $Filename4 or $Filename5 or $Filename6 or $Filename7 or $Filename8 or $Host1 or $Host2 or $Host3 or $Host4 or $Host5 or $Host6 or $Host7 or $Host8 or $Host9 or $Host10 or $URL11 or $URL12 or $Filename9 or $Host11 or $Host12 or $URL13 or $Filename10 or $Host13 or $URL14 or $Host14 or $URL15 or $URL16 or $Filename11 or $Host15 or $Host16 or $URL17 or $URL18 or $URL19 or $URL20 or $URL21 or $URL22 or $URL23 or $URL24 or $URL25
}