rule Evolution_Drivers_Duqu_Stuxnet
{
	strings:
		$Filename1 = "Mrxcls.sys"
		$Filename2 = "Mrxcls.sys"
		$Filename3 = "Mrxnet.sys"
		$Filename4 = "Jmidebs.sys"
		$Filename5 = "mrxcls.sys"
		$Filename6 = "mrxnet.sys"
		$Filename7 = "mrxnet.sys"
		$Filename8 = "mrxcls.sys"
		$Filename9 = "mrxnet.sys"
		$Filename10 = "jmidebs.sys"
		$Filename11 = "mrxcls.sys"
		$Filename12 = "Jmidebs.sys"
		$Filename13 = "rtniczw.sys"
		$Filename14 = "mrxcls.sys"
		$Filename15 = "rtniczw.sys"
		$Filename16 = "mrxcls.sys"
		$Filename17 = "rtniczw.sys"
		$Filename18 = "mrxcls.sys"
		$Filename19 = "rtniczw.sys"
		$MD51 = "546C4BBEBF02A1604EB2CAAAD4974DE0"
		$Filename20 = "rtniczw.sys"
		$Filename21 = "rtniczw.sys"
		$Filename22 = "rtniczw.sys"
		$Filename23 = "mrxcls.sys"
		$Filename24 = "rtniczw.sys"
		$Filename25 = "mrxcls.sys"
		$Filename26 = "rndismpc.sys"
		$Filename27 = "rndismpc.sys"
		$Filename28 = "mrxcls.sys"
		$Filename29 = "rndismpc.sys"
		$MD52 = "9AEC6E10C5EE9C05BED93221544C783E"
		$Filename30 = "rtniczw.sys"
		$Filename31 = "rndismpc.sys"
		$Filename32 = "mrxcls.sys"
		$Filename33 = "jmidebs.sys"
		$Filename34 = "rndismpc.sys"
		$Filename35 = "mrxcls.sys"
		$Filename36 = "mrxcls.sys"
		$Filename37 = "rtniczw.sys"
		$Filename38 = "jmidebs.sys"
		$Filename39 = "jmidebs.sys"
		$Filename40 = "mrxcls.sys"
		$Filename41 = "rndismpc.sys"
		$Filename42 = "rtniczw.sys"
		$Filename43 = "jmidebs.sys"
		$Filename44 = "rndismpc.sys"
		$Filename45 = "rtniczw.sys"
		$Filename46 = "jmidebs.sys"
		$Filename47 = "rtniczw.sys"
		$Filename48 = "mrxcls.sys"
		$Filename49 = "rtniczw.sys"
		$Filename50 = "jmidebs.sys"
	condition:
		$Filename1 or $Filename2 or $Filename3 or $Filename4 or $Filename5 or $Filename6 or $Filename7 or $Filename8 or $Filename9 or $Filename10 or $Filename11 or $Filename12 or $Filename13 or $Filename14 or $Filename15 or $Filename16 or $Filename17 or $Filename18 or $Filename19 or $MD51 or $Filename20 or $Filename21 or $Filename22 or $Filename23 or $Filename24 or $Filename25 or $Filename26 or $Filename27 or $Filename28 or $Filename29 or $MD52 or $Filename30 or $Filename31 or $Filename32 or $Filename33 or $Filename34 or $Filename35 or $Filename36 or $Filename37 or $Filename38 or $Filename39 or $Filename40 or $Filename41 or $Filename42 or $Filename43 or $Filename44 or $Filename45 or $Filename46 or $Filename47 or $Filename48 or $Filename49 or $Filename50
}