rule GlobalThreatIntelReport
{
	strings:
		$Host1 = "parmanpower.com"
		$Host2 = "usa.gov.us"
		$Email1 = "info@usa.gov"
		$Email2 = "ajaxtm@gmail.com"
		$Filename1 = "cmd.exe"
		$Host3 = "proxyme.net"
		$Filename2 = "ly-telegraph-many-websites-hijacked.html"
		$Filename3 = "my-hacks-international-business-times.html"
		$Host4 = "techworm.net"
		$URL1 = "http://vk.com/syrianelectronicarmy"
		$URL2 = "https://ello.co/syrianelectronicarmy"
		$URL3 = "https://www.pinterest.com/officialsea"
		$URL4 = "http://instagram.com/official_sea2"
		$URL5 = "https://www.youtube.com/user/SEAOfficialChannel"
		$URL6 = "https://twitter.com/official_sea16"
		$Host5 = "vk.com"
		$Host6 = "ello.co"
		$Host7 = "instagram.com"
		$Host8 = "sea.sy"
		$CVE1 = "CVE-2014-0322"
		$Host9 = "newss.effers.com"
		$Host10 = "savmpet.com"
		$Host11 = "gifas.assso.net"
		$Host12 = "icbcqsz.com"
		$Host13 = "oa.ameteksen.com"
		$CVE2 = "CVE-2014-4113"
		$Filename4 = "Win64.exe"
		$IP1 = "199.91.173.45"
		$Filename5 = "Pakistan.scr"
		$Host14 = "verizon.proxydns.com"
		$Host15 = "www.gobackto.net"
		$Host16 = "authorizeddns.org"
		$Host17 = "googlesupport.proxydns.com"
		$Host18 = "dns.dubkill.com"
		$URL7 = "http://blog.crowdstrike.com"
		$Host19 = "todaynews.dns-dns.com"
		$URL8 = "http://bits.blogs.nytimes"
		$URL9 = "http://resources.crowdstrike.com/putterpanda"
		$IP2 = "223.29.248.9"
		$IP3 = "202.181.133.237"
		$IP4 = "61.78.34.179"
		$IP5 = "203.135.134.243"
		$Filename6 = "sethc.exe"
	condition:
		$Host1 or $Host2 or $Email1 or $Email2 or $Filename1 or $Host3 or $Filename2 or $Filename3 or $Host4 or $URL1 or $URL2 or $URL3 or $URL4 or $URL5 or $URL6 or $Host5 or $Host6 or $Host7 or $Host8 or $CVE1 or $Host9 or $Host10 or $Host11 or $Host12 or $Host13 or $CVE2 or $Filename4 or $IP1 or $Filename5 or $Host14 or $Host15 or $Host16 or $Host17 or $Host18 or $URL7 or $Host19 or $URL8 or $URL9 or $IP2 or $IP3 or $IP4 or $IP5 or $Filename6
}