rule Micro_Targeted_Malvertising_WP_10_27_14_1
{
	strings:
		$Host1 = "earthlink.net"
		$Filename1 = "fvJcrgR0.exe"
		$Filename2 = "fvJcrgR0.exe"
		$Filename3 = "fvJcrgR0.exe"
		$Filename4 = "rundll32.exe"
		$Host2 = "delivery.first-impression.com"
		$Host3 = "earthlink.net"
		$Host4 = "earthlink.net"
		$Host5 = "earthlink.net"
		$Host6 = "delivery.first-impression.com"
		$Host7 = "earthlink.net"
		$IP1 = "24.234.123.133"
		$IP2 = "24.234.123.133"
		$Host8 = "impression.com"
		$Host9 = "thanhniennews.co"
		$URL1 = "http://indexexchange.com"
		$URL2 = "http://www.sitescout.com/rtb"
		$URL3 = "http://first-impression.com/home"
		$Filename5 = "Oajvliewxpge.exe"
		$Host10 = "www.sovrn.com"
		$Host11 = "www.turn.com"
		$Host12 = "indexexchange.com"
		$Host13 = "www.dataxu.com"
		$Host14 = "www.sitescout.com"
		$Host15 = "first-impression.com"
		$Host16 = "www.zedo.com"
		$Host17 = "ua.in"
		$Host18 = "first-impression.com"
		$Host19 = "impression.com"
		$Filename6 = "obupdat.exe"
		$Host20 = "first-impression.com"
		$Host21 = "first-impression.com"
		$Host22 = "theblaze.com"
		$Host23 = "www.searchtempest.com"
		$Host24 = "viewmixed.com"
		$Host25 = "lucianne.com"
		$Host26 = "thanhniennews.com"
		$Host27 = "mariowiki.com"
		$URL4 = "http://www.rubiconproject.com/privacy/consumer-online-profile-and-opt-out"
		$URL5 = "http://preferences-mgr.truste.com"
		$URL6 = "http://www.ghosteryenterprise.com/global-opt-out"
		$Host28 = "www.rubiconproject.com"
		$Host29 = "preferences-mgr.truste.com"
		$Host30 = "www.ghosteryenterprise.com"
	condition:
		$Host1 or $Filename1 or $Filename2 or $Filename3 or $Filename4 or $Host2 or $Host3 or $Host4 or $Host5 or $Host6 or $Host7 or $IP1 or $IP2 or $Host8 or $Host9 or $URL1 or $URL2 or $URL3 or $Filename5 or $Host10 or $Host11 or $Host12 or $Host13 or $Host14 or $Host15 or $Host16 or $Host17 or $Host18 or $Host19 or $Filename6 or $Host20 or $Host21 or $Host22 or $Host23 or $Host24 or $Host25 or $Host26 or $Host27 or $URL4 or $URL5 or $URL6 or $Host28 or $Host29 or $Host30
}