rule oil_tanker_en
{
	strings:
		$Host1 = "pandasecurity.com"
		$Filename1 = "deca.bat"
		$Filename2 = "pic.pdf"
		$Filename3 = "deca.bat"
		$Filename4 = "dcp.exe"
		$Filename5 = "unzip2.exe"
		$Filename6 = "bare.zip"
		$Filename7 = "dcp.exe"
		$Filename8 = "unzip.exe"
		$Filename9 = "bar.zip"
		$Filename10 = "ici.bat"
		$Filename11 = "aagi.bat"
		$Filename12 = "iei.bat"
		$Filename13 = "iewi.bat"
		$Filename14 = "deca.bat"
		$Filename15 = "pic.pdf"
		$Filename16 = "dcp.exe"
		$Filename17 = "unzip.exe"
		$Filename18 = "bare.zip"
		$Filename19 = "ici.bat"
		$Filename20 = "aagi.bat"
		$Filename21 = "image.exe"
		$Filename22 = "images.exe"
		$Filename23 = "viewer.exe"
		$Filename24 = "mdei.exe"
		$Filename25 = "ici.bat"
		$Filename26 = "aagi.bat"
		$Filename27 = "iei.bat"
		$Filename28 = "iewi.bat"
		$Filename29 = "iei.bat"
		$Filename30 = "iewi.bat"
		$Filename31 = "aagi.bat"
		$Filename32 = "ici.bat"
		$Filename33 = "iei.bat"
		$Filename34 = "iewi.bat"
		$Filename35 = "image.exe"
		$Filename36 = "images.exe"
		$Filename37 = "viewer.exe"
		$Host2 = "pandasecurity.com"
	condition:
		$Host1 or $Filename1 or $Filename2 or $Filename3 or $Filename4 or $Filename5 or $Filename6 or $Filename7 or $Filename8 or $Filename9 or $Filename10 or $Filename11 or $Filename12 or $Filename13 or $Filename14 or $Filename15 or $Filename16 or $Filename17 or $Filename18 or $Filename19 or $Filename20 or $Filename21 or $Filename22 or $Filename23 or $Filename24 or $Filename25 or $Filename26 or $Filename27 or $Filename28 or $Filename29 or $Filename30 or $Filename31 or $Filename32 or $Filename33 or $Filename34 or $Filename35 or $Filename36 or $Filename37 or $Host2
}