rule The_Madi_Infostealers
{
	strings:
		$Filename1 = "UpdateOffice.exe"
		$Filename2 = "PrintHoodUpdateOffice.exe"
		$Filename3 = "nam.dll"
		$Filename4 = "Templatesnam.dll"
		$Filename5 = "UUUU.htm"
		$Filename6 = "UeUeUeUe.htm"
		$Filename7 = "iexplore.exe"
		$Filename8 = "Iexplore.exe"
		$Filename9 = "fsdiskget.dll"
		$Filename10 = "nrbindek.dll"
		$Filename11 = "specialfile.dll"
		$Filename12 = "filesend.xls"
		$Filename13 = "filebind.xls"
		$Filename14 = "First.dll"
		$Filename15 = "first.dll"
		$URL1 = "http://C&C/abaanu5MYCOMPUTER-8712422C6C7704EF/dastor/file.htm"
		$Filename16 = "file.htm"
		$Filename17 = "das.htm"
		$Filename18 = "dast.xls"
		$Filename19 = "Update.dll"
		$Filename20 = "delete.dll"
		$Filename21 = "update.dll"
		$Filename22 = "lbdiskgo.dll"
		$Filename23 = "fskdiskget.dll"
		$Filename24 = "Specialfile.dll"
		$Filename25 = "logfi.dll"
		$Filename26 = "logfil.dll"
		$Filename27 = "winmm.dll"
		$Filename28 = "solt.html"
		$Filename29 = "cmd.exe"
		$Filename30 = "solt.htm"
		$Filename31 = "Filebind.xls"
		$Filename32 = "Sendfilejj.html"
		$Filename33 = "Filesend.xls"
		$Filename34 = "rafteha.zip"
		$Filename35 = "fileomade.xls"
		$Filename36 = "pangtkp.bat"
		$Filename37 = "1iexplore.exe"
		$Filename38 = "raftehacool.zip"
		$Filename39 = "pangtipo.bat"
		$Filename40 = "pangtip.bat"
		$Filename41 = "pangip.bat"
		$Filename42 = "srAntiq.dll"
		$Filename43 = "OfficeUpdate.exe"
		$Filename44 = "soltanik.dll"
		$Filename45 = "res.exe"
		$Filename46 = "soltanik.exe"
		$Filename47 = "ladine.dll"
		$Filename48 = "ReReReRe.htm"
		$Filename49 = "ReReReRe.html"
		$URL2 = "http://C&CIP/ASLK//asgari/mah/ReReReRe.htm"
		$Filename50 = "ASLASLKK223.dll"
		$Filename51 = "ASLASLKK224.dll"
		$Filename52 = "Res.exe"
		$Filename53 = "SeSeSeSe.htm"
		$Filename54 = "ASLASLKK2231.dll"
		$Filename55 = "ASLASLKK2241.dll"
		$Filename56 = "Ladine.dll"
		$Filename57 = "SSSS.htm"
		$Filename58 = "Soltanik.exe"
		$Filename59 = "server.exe"
		$Filename60 = "Server.exe"
	condition:
		$Filename1 or $Filename2 or $Filename3 or $Filename4 or $Filename5 or $Filename6 or $Filename7 or $Filename8 or $Filename9 or $Filename10 or $Filename11 or $Filename12 or $Filename13 or $Filename14 or $Filename15 or $URL1 or $Filename16 or $Filename17 or $Filename18 or $Filename19 or $Filename20 or $Filename21 or $Filename22 or $Filename23 or $Filename24 or $Filename25 or $Filename26 or $Filename27 or $Filename28 or $Filename29 or $Filename30 or $Filename31 or $Filename32 or $Filename33 or $Filename34 or $Filename35 or $Filename36 or $Filename37 or $Filename38 or $Filename39 or $Filename40 or $Filename41 or $Filename42 or $Filename43 or $Filename44 or $Filename45 or $Filename46 or $Filename47 or $Filename48 or $Filename49 or $URL2 or $Filename50 or $Filename51 or $Filename52 or $Filename53 or $Filename54 or $Filename55 or $Filename56 or $Filename57 or $Filename58 or $Filename59 or $Filename60
}