rule w32_stuxnet_dossier
{
	strings:
		$Filename1 = "MrxNet.sys"
		$Filename2 = "MRxnet.sys"
		$Filename3 = "Win32k.sys"
		$Filename4 = "Ntdll.dll"
		$Filename5 = "avp.exe"
		$Filename6 = "Mcshield.exe"
		$Filename7 = "avguard.exe"
		$Filename8 = "bdagent.exe"
		$Filename9 = "UmxCfg.exe"
		$Filename10 = "fsdfwd.exe"
		$Filename11 = "rtvscan.exe"
		$Filename12 = "ccSvcHst.exe"
		$Filename13 = "ekrn.exe"
		$Filename14 = "tmpproxy.exe"
		$Filename15 = "Lsass.exe"
		$Filename16 = "Winlogon.exe"
		$Filename17 = "Svchost.exe"
		$Filename18 = "1.zip"
		$Filename19 = "csrss.exe"
		$Filename20 = "win32k.sys"
		$Filename21 = "services.exe"
		$Filename22 = "Mrxnet.sys"
		$Filename23 = "S7tgtopx.exe"
		$Filename24 = "explorer.exe"
		$Filename25 = "MrxCls.sys"
		$Filename26 = "Mrxcls.sys"
		$Filename27 = "mrxcls.sys"
		$Filename28 = "CCProjectMgr.exe"
		$Filename29 = "s7tgtopx.exe"
		$Filename30 = "Explorer.exe"
		$Filename31 = "iexplore.exe"
		$Host1 = "www.mypremierfutbol.com"
		$Host2 = "www.todaysfutbol.com"
		$URL1 = "http://]www.mypremierfutbol.com/index.php?data=1234"
		$Filename32 = "mrxnet.sys"
		$Filename33 = "lsass.exe"
		$Filename34 = "winsta.exe"
		$Filename35 = "Winsta.exe"
		$Filename36 = "Kernel32.dll"
		$Filename37 = "Netapi32.dll"
		$CVE1 = "CVE-2010-2568"
		$Filename38 = "kernel32.dll"
		$Filename39 = "shell32.dll"
		$Filename40 = "s7apromx.dll"
		$Filename41 = "mfc42.dll"
		$Filename42 = "msvcrt.dll"
		$Filename43 = "ccprojectmgr.exe"
		$Filename44 = "xyz.dll"
		$Filename45 = "s7otbxdx.dll"
		$Filename46 = "s7otbxsx.dll"
		$Filename47 = "ccrtsloader.exe"
		$Filename48 = "s7otbldx.dll"
	condition:
		$Filename1 or $Filename2 or $Filename3 or $Filename4 or $Filename5 or $Filename6 or $Filename7 or $Filename8 or $Filename9 or $Filename10 or $Filename11 or $Filename12 or $Filename13 or $Filename14 or $Filename15 or $Filename16 or $Filename17 or $Filename18 or $Filename19 or $Filename20 or $Filename21 or $Filename22 or $Filename23 or $Filename24 or $Filename25 or $Filename26 or $Filename27 or $Filename28 or $Filename29 or $Filename30 or $Filename31 or $Host1 or $Host2 or $URL1 or $Filename32 or $Filename33 or $Filename34 or $Filename35 or $Filename36 or $Filename37 or $CVE1 or $Filename38 or $Filename39 or $Filename40 or $Filename41 or $Filename42 or $Filename43 or $Filename44 or $Filename45 or $Filename46 or $Filename47 or $Filename48
}