rule WhitePaper_HBGary_Threat_Report__Operation_Aurora
{
	strings:
		$Host1 = "3322.org"
		$Filename1 = "aaa.gif"
		$URL1 = "http://demo1.ftpaccess.cc"
		$Filename2 = "a.exe"
		$Filename3 = "b.exe"
		$Filename4 = "ad.jpg"
		$Filename5 = "Kernel32.dll"
		$Filename6 = "user32.dll"
		$Filename7 = "svchost.exe"
		$Host2 = "demo1.ftpaccess.cc"
		$Host3 = "sl1.homelinux.org"
		$Host4 = "360.homeunix.com"
		$Host5 = "ftp2.homeunix.com"
		$Host6 = "update.ourhobby.com"
		$Host7 = "blog1.servebeer.com"
		$Host8 = "ftpaccess.cc"
		$Host9 = "www.trustedsource.org"
		$Filename8 = "securmon.dll"
		$Filename9 = "AppMgmt.dll"
		$Filename10 = "A0029670.dll"
		$Filename11 = "g32.sys"
		$Filename12 = "VedioDriver.dll"
		$Filename13 = "acelpvc.dll"
		$Filename14 = "wuauclt.exe"
		$Filename15 = "jucheck.exe"
		$Filename16 = "AdobeUpdateManager.exe"
		$Filename17 = "zf32.dll"
		$Filename18 = "rasmon.dll"
		$Host10 = "homeunix.com"
		$Host11 = "homelinux.com"
		$Host12 = "ourhobby.com"
		$Host13 = "2288.org"
		$Host14 = "8866.org"
		$Host15 = "ath.cx"
		$Host16 = "33iqst.com"
		$Host17 = "dyndns.org"
		$Host18 = "linode.com"
		$Host19 = "loups.info"
		$Host20 = "blogsite.org"
		$Registry1 = "HKLM\\Software\\Sun\\1"
		$Filename19 = "AuroraInnoculation.exe"
		$URL2 = "http://www.thetechherald.com/article.php/201004"
		$URL3 = "http://www.fjbmcu.com/chengxu/crcsuan.htm"
		$URL4 = "http://www.avertlabs.com/research/blog/index.php/2010/01/18/an"
		$Filename20 = "crcsuan.htm"
		$Host21 = "www.thetechherald.com"
		$Host22 = "www.fjbmcu.com"
		$Host23 = "www.avertlabs.com"
		$Email1 = "info@hbgary.com"
		$Email2 = "support@hbgary.com"
	condition:
		$Host1 or $Filename1 or $URL1 or $Filename2 or $Filename3 or $Filename4 or $Filename5 or $Filename6 or $Filename7 or $Host2 or $Host3 or $Host4 or $Host5 or $Host6 or $Host7 or $Host8 or $Host9 or $Filename8 or $Filename9 or $Filename10 or $Filename11 or $Filename12 or $Filename13 or $Filename14 or $Filename15 or $Filename16 or $Filename17 or $Filename18 or $Host10 or $Host11 or $Host12 or $Host13 or $Host14 or $Host15 or $Host16 or $Host17 or $Host18 or $Host19 or $Host20 or $Registry1 or $Filename19 or $URL2 or $URL3 or $URL4 or $Filename20 or $Host21 or $Host22 or $Host23 or $Email1 or $Email2
}