rule WickedRose_andNCPH
{
	strings:
		$URL1 = "http://www.study-in-china.org/school/Sichuan/suse"
		$Host1 = "www.suse.edu.cn"
		$Host2 = "www.study-in-china.org"
		$Filename1 = "5-16-2006.doc"
		$Filename2 = "winguis.dll"
		$Host3 = "nease.net"
		$URL2 = "http://rodag.blogbus.com/index.html"
		$Filename3 = "index.html"
		$Host4 = "rodag.blogbus.com"
		$Host5 = "enjoy.irdet.com"
		$Host6 = "enjoy.bmwsee.com"
		$Host7 = "windowsupdates.net"
		$Host8 = "windowsupdates.net"
		$Host9 = "windowsupdates.net"
		$Host10 = "windowsupdates.net"
		$Host11 = "www.mghacker.com"
		$Host12 = "www.mghacker.com"
		$URL3 = "http://rodag.blogbus.com"
		$URL4 = "http://www.cppblog.com/charles"
		$URL5 = "http://kungbim.blogbus.com"
		$Host13 = "www.mghacker.com"
		$Host14 = "rodag.blogbus.com"
		$Host15 = "www.cppblog.com"
		$Host16 = "kungbim.blogbus.com"
		$Host17 = "www.ncph.net"
		$Host18 = "ncph.net"
		$Host19 = "www.ncph.net"
		$Host20 = "126.com"
		$Email1 = "ncph2005@126.com"
		$Host21 = "163.com"
		$Host22 = "cnasm.com"
		$Host23 = "tthacker.cublog.cn"
		$Host24 = "windowsupdates.net"
		$Email2 = "whg@163.com"
	condition:
		$URL1 or $Host1 or $Host2 or $Filename1 or $Filename2 or $Host3 or $URL2 or $Filename3 or $Host4 or $Host5 or $Host6 or $Host7 or $Host8 or $Host9 or $Host10 or $Host11 or $Host12 or $URL3 or $URL4 or $URL5 or $Host13 or $Host14 or $Host15 or $Host16 or $Host17 or $Host18 or $Host19 or $Host20 or $Email1 or $Host21 or $Host22 or $Host23 or $Host24 or $Email2
}