rule wp_global_energy_cyberattacks_night_dragon
{
	strings:
		$Host1 = "net.cn"
		$Filename1 = "zwShell.exe"
		$Filename2 = "zwShell.exe"
		$Filename3 = "server.exe"
		$Filename4 = "svchost.exe"
		$Filename5 = "startup.dll"
		$Filename6 = "connect.dll"
		$Filename7 = "Connect.dll"
		$Filename8 = "PluginFile.dll"
		$Filename9 = "PluginScreen.dll"
		$Filename10 = "PluginCmd.dll"
		$Filename11 = "PluginKeyboard.dll"
		$Filename12 = "PluginProcess.dll"
		$Filename13 = "PluginService.dll"
		$Filename14 = "PluginRegedit.dll"
		$Filename15 = "Startup.dll"
		$Registry1 = "HKLM\\system"
		$Registry2 = "HKLM\\Software\\RAT"
		$MD51 = "093640a69c8eafbc60343bf9cd1d3ad3"
		$MD52 = "85df6b3e2c1a4c6ce20fc8080e0b53e9"
		$MD53 = "A6CBA73405C77FEDEAF4722AD7D35D60"
		$MD54 = "6E31CCA77255F9CDE228A2DB9E2A3855"
		$URL1 = "http://office-on-the.net"
		$Host2 = "is-a-chef.com"
		$Host3 = "thruhere.net"
		$Host4 = "office-on-the.net"
		$Host5 = "selfip.com"
		$Host6 = "is-a-chef.com"
		$Host7 = "is-a-chef.com"
		$Host8 = "thruhere.net"
		$Host9 = "thruhere.net"
		$Host10 = "on-the.net"
		$Host11 = "office-on-the.net"
		$Host12 = "selfip.com"
		$Host13 = "selfip.com"
		$URL2 = "https://www.webimmune.net/default.asp"
		$Host14 = "www.webimmune.net"
		$Email1 = "virus_research@mcafee.com"
		$URL3 = "http://www.hackingexposed.com"
		$Host15 = "foundstone.com"
		$Host16 = "avertlabs.com"
		$Host17 = "www.hackingexposed.com"
		$Email2 = "incidentresponse@foundstone.com"
		$Filepath1 = "C:\\Windows"
		$Filename16 = "svchost.exe"
		$Filename17 = "svchost.exe"
	condition:
		$Host1 or $Filename1 or $Filename2 or $Filename3 or $Filename4 or $Filename5 or $Filename6 or $Filename7 or $Filename8 or $Filename9 or $Filename10 or $Filename11 or $Filename12 or $Filename13 or $Filename14 or $Filename15 or $Registry1 or $Registry2 or $MD51 or $MD52 or $MD53 or $MD54 or $URL1 or $Host2 or $Host3 or $Host4 or $Host5 or $Host6 or $Host7 or $Host8 or $Host9 or $Host10 or $Host11 or $Host12 or $Host13 or $URL2 or $Host14 or $Email1 or $URL3 or $Host15 or $Host16 or $Host17 or $Email2 or $Filepath1 or $Filename16 or $Filename17
}